# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "DemoProject" do

pod 'CocoaSecurity', '~> 1.2'
pod 'DKPassword', '~> 0.0'

end

target "DemoProjectTests" do

end

